/* Alle MCU-Kinofilme und Disney+-Realserien (Marvel Studios / Marvel
   Television), gruppiert nach den offiziellen Marvel-Phasen 1–6.
   Innerhalb jeder Phase ist alles chronologisch nach der Handlung
   sortiert (angelehnt an Marvels offizielle Timeline-Reihenfolge), nicht
   nach Kinostart – z. B. steht in Phase 1 Captain Marvel (1995) direkt
   nach Captain America: The First Avenger.
   Animierte Serien und die Special Presentations bleiben bewusst außen vor.

   Pro Eintrag:
     period = Handlungszeitraum im MCU (erscheint unter dem Zeitstrahl;
              bei den neuesten/kommenden Titeln näherungsweise bzw. "20??")
     date   = US-Kinostart bzw. Disney+-Start (erscheint in der Infobox)
     series = true markiert eine Serie: „Serie“-Badge, Infobox zeigt
              „Disney+-Start“. Staffeln mit eigener Phase (Loki, Daredevil)
              stehen als eigene Einträge und teilen sich einen Logo-Slug.

   Logos: Lege ein transparentes PNG unter  assets/logos/<slug>.png  ab
   (z. B. assets/logos/iron-man.png). Fehlt die Datei, zeigt die Seite
   automatisch den stilisierten Filmtitel als Platzhalter an.

   story = Liste der Key Moments (ganze Sätze, ein Eintrag pro Punkt);
   erscheint zusammen mit characters in der Hover-Infobox über dem
   Filmtitel (als Aufzählung gerendert in main.js, gestylt als
   .movie-tip im CSS).

   streaming = Liste der Dienste, bei denen der Titel streambar ist
   (Logos unter assets/streaming services/, Zuordnung in main.js).
   Ohne Angabe gilt: Disney+ – außer bei upcoming-Titeln, dort bleibt
   der Streaming-Bereich der Infobox ausgeblendet. Nur die Sony-
   Spider-Man-Filme weichen ab (streaming: ["prime"]).

   nebula = [Akzent A, Akzent B, kühle Basis] als RGB-Werte für die
   Galaxie-Nebel der jeweiligen Phase. accent = Akzentfarbe fürs UI. */

const PHASES = [
  {
    num: 1,
    id: "phase-1",
    title: "Phase One",
    saga: "The Infinity Saga",
    years: "2008 – 2012",
    accent: "#4d8cff",
    nebula: [[72, 140, 255], [56, 84, 230], [140, 80, 230]],
    movies: [
      {
        title: "Captain America: The First Avenger",
        period: "1943 – 1945",
        date: "22. Juli 2011",
        slug: "captain-america-the-first-avenger",
        story: [
          "Johann Schmidt findet 1942 in Norwegen den Tesserakt. Sein Wissenschaftler Arnim Zola macht dessen Energie für HYDRA-Waffen nutzbar.",
          "Das Supersoldaten-Serum entstand einst aus der Forschung von Schmidt und Dr. Abraham Erskine. Es verstärkt alles im Menschen, das Gute wie das Böse.",
          "Schmidt injizierte sich das noch unfertige Serum und wurde durch die Nebenwirkungen zu Red Skull entstellt.",
          "Der schmächtige, aber gutherzige Steve Rogers wird von Erskine ausgewählt und mit dem fertigen Serum zu Captain America.",
          "Bei der Mission auf HYDRAs Zug stürzt Bucky Barnes in den Abgrund. Zola wird dort gefangen genommen.",
          "Im Finale greift Red Skull mit bloßer Hand nach dem Tesserakt und wird von ihm fort teleportiert.",
          "Steve opfert sich und stürzt den HYDRA-Bomber mitsamt dem Tesserakt an Bord ins ewige Eis.",
          "Howard Stark begleitet Steve den ganzen Weg. Er betreute das Serum-Experiment, gab ihm das Vibranium-Schild, flog ihn zu Missionen und suchte nach dem Absturz jahrelang nach ihm. Bei dieser Suche barg er den Tesserakt aus dem Meer.",
          "Knapp 70 Jahre später erwacht Steve in der Gegenwart und findet sich in einer völlig fremden Welt wieder.",
        ],
        characters: ["Steve Rogers / Captain America", "Peggy Carter", "Bucky Barnes", "Johann Schmidt / Red Skull", "Howard Stark"],
      },
      {
        title: "Captain Marvel",
        period: "1995",
        date: "8. März 2019",
        slug: "captain-marvel",
        story: [
          "Die Kree-Kriegerin „Vers“ lebt ohne Erinnerungen auf Hala und wird von Yon-Rogg zur Elitesoldatin ausgebildet.",
          "Nach ihrer Gefangennahme durch die Skrulls stürzt sie 1995 auf die Erde, wo Bruchstücke ihrer Vergangenheit hochkommen.",
          "Mit dem jungen S.H.I.E.L.D.-Agenten Nick Fury findet sie heraus, dass sie die totgeglaubte Testpilotin Carol Danvers ist.",
          "Ihre Kräfte stammen aus der Explosion eines experimentellen Triebwerks, das Mar-Vell aus der Energie des Tesserakts entwickelt hatte.",
          "Die große Wende folgt, als sich zeigt, dass die Skrulls keine Monster sind, sondern Flüchtlinge in einem Vernichtungskrieg der Kree.",
          "Carol sprengt den Kree-Blocker, der ihre Kräfte begrenzte, entfesselt ihre volle Macht und schlägt Ronans Flotte im Alleingang zurück.",
          "Fury verliert sein Auge an die Flerken-„Katze“ Goose, die kurzerhand auch den Tesserakt verschluckt.",
          "Zum Abschied gibt Carol Fury einen Pager für Notfälle und inspiriert ihn zur Avengers-Initiative, benannt nach ihrem Rufzeichen „Avenger“.",
        ],
        characters: ["Carol Danvers / Captain Marvel", "Nick Fury", "Talos", "Yon-Rogg", "Maria Rambeau", "Goose"],
      },
      {
        title: "Iron Man",
        period: "2008",
        date: "2. Mai 2008",
        slug: "iron-man",
        story: [
          "Waffenmogul Tony Stark wird in Afghanistan von den Zehn Ringen entführt. Granatsplitter wandern seitdem langsam auf sein Herz zu.",
          "Sein Mitgefangener Ho Yinsen hält ihn mit einem Elektromagneten am Leben, aus dem Tony den ersten Arc-Reaktor entwickelt.",
          "Statt der geforderten Rakete bauen die beiden heimlich die klobige Mark-I-Rüstung. Yinsen opfert sich bei der Flucht.",
          "Zurück in den USA stoppt Tony die Waffenproduktion seiner Firma und perfektioniert die Rüstung zum ikonischen Mark III.",
          "Sein Mentor Obadiah Stane steckt hinter der Entführung und verkauft heimlich Stark-Waffen an Terroristen.",
          "Stane stiehlt Tonys Reaktor aus dessen Brust und baut daraus den Iron Monger. Im Finale überlädt Pepper den großen Arc-Reaktor, und Stane stirbt.",
          "Auf der Pressekonferenz wirft Tony das vorbereitete Skript beiseite und erklärt der Welt: „I am Iron Man.“ Nach dem Abspann spricht Nick Fury ihn erstmals auf die Avengers-Initiative an.",
        ],
        characters: ["Tony Stark / Iron Man", "Pepper Potts", "James Rhodes", "Obadiah Stane", "Nick Fury"],
      },
      {
        title: "Iron Man 2",
        period: "2010",
        date: "7. Mai 2010",
        slug: "iron-man-2",
        story: [
          "Das Palladium im Arc-Reaktor, das Tony am Leben hält, vergiftet ihn schleichend. Er verheimlicht es und verhält sich zunehmend selbstzerstörerisch.",
          "Ivan Vanko, der Sohn von Howard Starks verstoßenem Partner Anton Vanko, baut einen eigenen Reaktor und attackiert Tony als Whiplash beim Rennen in Monaco.",
          "Rüstungskonkurrent Justin Hammer befreit Vanko aus dem Gefängnis und lässt ihn heimlich eine Drohnenarmee bauen.",
          "Rhodey schnappt sich die Mark-II-Rüstung und wird zu War Machine. Natasha Romanoff schleust sich als „Natalie Rushman“ bei Stark Industries ein und gibt so ihr Debüt als Black Widow.",
          "In Howard Starks Nachlass entdeckt Tony den versteckten Bauplan für ein neues Element. Er synthetisiert es und heilt damit seine Vergiftung.",
          "Auf der Stark Expo übernehmen Vankos Drohnen die Kontrolle. Tony und Rhodey besiegen sie und Whiplash Seite an Seite.",
        ],
        characters: ["Tony Stark / Iron Man", "Natasha Romanoff / Black Widow", "James Rhodes / War Machine", "Ivan Vanko / Whiplash", "Pepper Potts", "Nick Fury"],
      },
      {
        title: "The Incredible Hulk",
        period: "2010",
        date: "13. Juni 2008",
        slug: "the-incredible-hulk",
        story: [
          "Ein missglücktes Gamma-Experiment machte Bruce Banner zum Hulk. Seitdem ist er vor General Ross auf der Flucht.",
          "Untergetaucht in Brasilien sucht er mit dem anonymen Kontakt „Mr. Blue“ nach einem Heilmittel. Dahinter steckt der Wissenschaftler Samuel Sterns.",
          "Ross spürt ihn auf. Sein Elitesoldat Emil Blonsky lässt sich ein Supersoldaten-Serum verabreichen, um mit dem Hulk mithalten zu können.",
          "Sterns' Behandlung scheint den Hulk zu unterdrücken, doch direkt danach wird Banner von Ross gefasst.",
          "Blonsky zwingt Sterns, ihn zusätzlich mit Banners Blut zu behandeln, und mutiert zur Abomination.",
          "Banner stürzt sich freiwillig aus dem Helikopter, verwandelt sich und ringt die Abomination in Harlem nieder.",
          "Am Ende beginnt Banner im Exil, die Verwandlung zu kontrollieren. Tony Stark spricht Ross derweil auf ein „Team“ an.",
        ],
        characters: ["Bruce Banner / Hulk", "Betty Ross", "General Thaddeus Ross", "Emil Blonsky / Abomination"],
      },
      {
        title: "Thor",
        period: "2010",
        date: "6. Mai 2011",
        slug: "thor",
        story: [
          "Am Tag von Thors Krönung dringen Frostriesen in Asgard ein. Thor greift daraufhin eigenmächtig Jotunheim an und bricht damit den Frieden.",
          "Odin verbannt seinen arroganten Sohn machtlos auf die Erde und belegt Mjölnir mit einem Bann, sodass nur ein Würdiger den Hammer heben kann.",
          "In New Mexico trifft Thor die Astrophysikerin Jane Foster. Selbst mit aller Kraft bekommt er seinen eigenen Hammer nicht mehr vom Boden.",
          "Loki erfährt, dass er in Wahrheit der Sohn des Frostriesen-Königs Laufey ist. Als Odin in den Odinschlaf fällt, reißt er den Thron an sich.",
          "Loki schickt den Destroyer zur Erde. Thor opfert sich schutzlos für seine Freunde und wird genau dadurch wieder würdig.",
          "Zurück in Asgard stoppt Thor Lokis Plan, Jotunheim komplett zu vernichten, und zerschlägt dafür den Bifröst. Loki lässt sich daraufhin ins Nichts fallen.",
          "Nach dem Abspann zeigt Fury dem Wissenschaftler Selvig den Tesserakt, heimlich beobachtet von Loki.",
        ],
        characters: ["Thor", "Loki", "Jane Foster", "Odin", "Heimdall"],
      },
      {
        title: "Marvel's The Avengers",
        period: "2012",
        date: "4. Mai 2012",
        slug: "the-avengers",
        story: [
          "Loki kommt durch ein Tesserakt-Portal zur Erde, stiehlt den Würfel und versklavt Hawkeye und Professor Selvig mit seinem Zepter.",
          "Nick Fury aktiviert die Avengers-Initiative. Captain America, Iron Man und Black Widow holen Bruce Banner an Bord, und Thor stößt später dazu.",
          "Loki lässt sich in Stuttgart absichtlich festnehmen, denn er will das Team von innen spalten.",
          "Beim Angriff auf den Helicarrier rastet der Hulk aus, und Loki tötet Agent Coulson. Ausgerechnet dieser Tod schweißt die zerstrittenen Helden zusammen.",
          "Selvig öffnet über dem Stark Tower das Portal für die Chitauri-Invasion, und die Schlacht um New York beginnt.",
          "Erstmals kämpfen die Avengers als Einheit. Der Hulk verprügelt Loki dabei wie eine Stoffpuppe.",
          "Tony fliegt eine Atomrakete durchs Portal und zerstört das Chitauri-Mutterschiff. Natasha schließt das Portal mit dem Zepter.",
          "Thor bringt Loki und den Tesserakt nach Asgard. Nach dem Abspann zeigt sich erstmals Thanos.",
        ],
        characters: ["Iron Man", "Captain America", "Thor", "Hulk", "Black Widow", "Hawkeye", "Loki", "Nick Fury"],
      },
    ],
  },
  {
    num: 2,
    id: "phase-2",
    title: "Phase Two",
    saga: "The Infinity Saga",
    years: "2013 – 2015",
    accent: "#ff4d4d",
    nebula: [[255, 72, 72], [205, 48, 140], [62, 72, 195]],
    movies: [
      {
        title: "Iron Man 3",
        period: "2012",
        date: "3. Mai 2013",
        slug: "iron-man-3",
        story: [
          "Seit der Schlacht um New York leidet Tony unter Panikattacken und Schlaflosigkeit und baut zwanghaft immer neue Anzüge.",
          "Ein Terrorist namens „der Mandarin“ verübt Anschläge, bei denen auch Happy schwer verletzt wird. Tony fordert ihn öffentlich heraus und verliert prompt sein Haus in Malibu an einen Raketenangriff.",
          "Gestrandet in Tennessee findet Tony heraus, dass hinter den vermeintlichen Bomben explodierende Extremis-Versuchspersonen stecken.",
          "Der große Twist folgt, als sich der Mandarin als harmloser Schauspieler namens Trevor Slattery entpuppt. Der wahre Drahtzieher ist Aldrich Killian, den Tony vor Jahren auf einer Party versetzt hatte.",
          "Killian entführt Pepper und den Präsidenten. Im Finale ruft Tony per „House Party Protocol“ seine gesamte Anzugflotte zu Hilfe.",
          "Am Ende ist es die mit Extremis infizierte Pepper, die Killian ausschaltet.",
          "Tony sprengt symbolisch alle Anzüge, lässt sich die Granatsplitter aus der Brust operieren und wirft seinen alten Reaktor ins Meer.",
        ],
        characters: ["Tony Stark / Iron Man", "Pepper Potts", "Aldrich Killian", "James Rhodes", "Happy Hogan"],
      },
      {
        title: "Thor: The Dark World",
        period: "2013",
        date: "8. Nov. 2013",
        slug: "thor-the-dark-world",
        story: [
          "Vor Urzeiten wollte der Dunkelelf Malekith mit dem Äther das Universum in Dunkelheit stürzen. Odins Vater nahm ihm die Waffe ab und versteckte sie.",
          "Während der Konvergenz, der seltenen Ausrichtung der neun Welten, findet Jane Foster den Äther, der von ihr Besitz ergreift.",
          "Thor bringt Jane nach Asgard, doch Malekith erwacht und greift an. Königin Frigga stirbt, als sie Jane beschützt.",
          "Für die Flucht nach Svartalfheim verbündet sich Thor ausgerechnet mit dem inhaftierten Loki.",
          "Malekith entzieht Jane den Äther. Loki täuscht im Kampf seinen Heldentod vor.",
          "Im Finale in Greenwich besiegt Thor Malekith, während die Konvergenz die Kämpfer durch Portale quer über die Welten schleudert.",
          "Der Äther, die flüssige Form des Realitätssteins, wird dem Collector übergeben. Auf Asgards Thron sitzt derweil Loki, getarnt als Odin.",
        ],
        characters: ["Thor", "Loki", "Jane Foster", "Malekith", "Frigga"],
      },
      {
        title: "Captain America: The Winter Soldier",
        period: "2014",
        date: "4. Apr. 2014",
        slug: "captain-america-the-winter-soldier",
        story: [
          "Steve arbeitet inzwischen für S.H.I.E.L.D. Bei einer Geiselbefreiung zieht Natasha heimlich Daten für Fury ab, und erste Risse im Vertrauen entstehen.",
          "Fury wird vom mysteriösen Winter Soldier niedergeschossen und stirbt scheinbar. Zuvor übergibt er Steve die Daten mit der Warnung, niemandem zu trauen.",
          "In einem alten Bunker entdecken Steve und Natasha Zolas konserviertes Bewusstsein. Es offenbart, dass HYDRA S.H.I.E.L.D. seit dessen Gründung unterwandert hat und auch Alexander Pierce dazugehört.",
          "HYDRAs Plan „Project Insight“ sieht vor, dass drei vernetzte Helicarrier Millionen potenzielle Bedrohungen präventiv eliminieren.",
          "Der Winter Soldier entpuppt sich als Bucky Barnes, der von HYDRA gehirngewaschen und seit 70 Jahren als Attentäter eingesetzt wird.",
          "Mit Sam Wilson alias Falcon und dem quicklebendigen Fury tauschen sie die Zielchips. Die Helicarrier schießen sich gegenseitig ab, und S.H.I.E.L.D. zerbricht vor den Augen der Welt.",
          "Bucky zieht Steve bewusstlos aus dem Potomac und verschwindet. Nach dem Abspann tauchen erstmals Wanda und Pietro Maximoff auf, die sich mitsamt dem Zepter in HYDRAs Gewahrsam befinden.",
        ],
        characters: ["Steve Rogers / Captain America", "Natasha Romanoff", "Bucky Barnes / Winter Soldier", "Sam Wilson / Falcon", "Nick Fury", "Alexander Pierce"],
      },
      {
        title: "Guardians of the Galaxy",
        period: "2014",
        date: "1. Aug. 2014",
        slug: "guardians-of-the-galaxy",
        story: [
          "1988 wird der kleine Peter Quill direkt nach dem Tod seiner Mutter von Yondus Ravagers entführt.",
          "Jahre später stiehlt Quill auf Morag einen mysteriösen Orb und gerät damit ins Visier des Kree-Fanatikers Ronan.",
          "Auf Xandar landen Quill, Gamora, Rocket und Groot gemeinsam im Hochsicherheitsgefängnis Kyln und brechen mit Drax wieder aus.",
          "Beim Collector erfahren sie, dass im Orb der Machtstein steckt, einer der sechs Infinity-Steine.",
          "Ronan reißt den Stein an sich, verrät Thanos und will Xandar im Alleingang vernichten.",
          "In der Schlacht um Xandar opfert sich Groot für seine Freunde: „We are Groot.“",
          "Quill fängt den Stein mit bloßer Hand. Nur weil die Guardians die Last gemeinsam tragen, überlebt er, und Ronan wird vernichtet.",
          "Der Stein bleibt beim Nova Corps. Quill erfährt, dass er nur zur Hälfte Mensch ist, und aus einem Steckling wächst Baby Groot.",
        ],
        characters: ["Peter Quill / Star-Lord", "Gamora", "Drax", "Rocket", "Groot", "Yondu", "Ronan", "Nebula"],
      },
      {
        title: "Guardians of the Galaxy Vol. 2",
        period: "2014",
        date: "5. Mai 2017",
        slug: "guardians-of-the-galaxy-vol-2",
        story: [
          "Bei einem Auftrag für die Sovereign klaut Rocket deren Batterien. Vor der Vergeltungsflotte rettet die Guardians ausgerechnet Ego, Quills lange verschollener Vater.",
          "Ego ist ein Celestial, ein uraltes Wesen in Gestalt eines lebenden Planeten. Bei ihm lebt die empathische Mantis.",
          "Yondu wird währenddessen von der eigenen Crew um Taserface gestürzt. Mit Rocket und Groot bricht er aus und richtet die Meuterer.",
          "Egos wahrer Plan ist die „Expansion“. Er will das gesamte Universum mit sich selbst überziehen und hat dafür bereits tausende eigene Kinder getötet.",
          "Auch den tödlichen Tumor von Quills Mutter pflanzte Ego ihr ein. Yondu behielt Peter damals, um ihn vor seinem Vater zu schützen.",
          "Im Finale zerstören die Guardians Egos Kern. Yondu opfert sich, um Quill zu retten: „Er mag dein Vater gewesen sein, aber er war nicht dein Daddy.“",
          "Nebula zieht allein los, um Thanos zu töten. In einer Abspannszene kündigen die Sovereign ihre neue Schöpfung namens Adam an.",
        ],
        characters: ["Star-Lord", "Ego", "Yondu", "Gamora", "Nebula", "Rocket", "Baby Groot", "Mantis"],
      },
      {
        title: "Avengers: Age of Ultron",
        period: "2015",
        date: "1. Mai 2015",
        slug: "avengers-age-of-ultron",
        story: [
          "Die Avengers erobern Lokis Zepter von HYDRA zurück. Dabei treffen sie erstmals auf die Zwillinge Wanda und Pietro Maximoff.",
          "Tony und Bruce erwecken mit der KI aus dem Gedankenstein heimlich das Friedensprogramm Ultron. Das kommt sofort zu dem Schluss, dass wahrer Frieden nur ohne die Menschheit möglich ist.",
          "Ultron verbündet sich mit den Zwillingen. Wandas Visionen destabilisieren das Team, und der manipulierte Hulk verwüstet Johannesburg, bis Tony ihn im Hulkbuster stoppt.",
          "Das Team taucht auf Hawkeyes geheimer Familienfarm unter. Clint hat Frau und Kinder, von denen niemand wusste.",
          "Als Wanda in Ultrons Geist dessen wahren Vernichtungsplan liest, wechseln die Zwillinge die Seiten.",
          "Aus Ultrons Vibranium-Körper und dem Gedankenstein entsteht Vision, den Thor per Blitz erweckt. Prompt erweist er sich als würdig, Mjölnir zu heben.",
          "Ultron hebt Sokovia in den Himmel, um es als Meteor auf die Erde stürzen zu lassen. Pietro stirbt, als er Hawkeye und ein Kind vor den Kugeln rettet.",
          "Nach dem Sieg formiert sich ein neues Avengers-Team um Wanda, Vision, Falcon und War Machine. Nach dem Abspann greift Thanos selbst zum Infinity-Handschuh.",
        ],
        characters: ["Die Avengers", "Ultron", "Wanda Maximoff", "Pietro Maximoff", "Vision"],
      },
      {
        title: "Ant-Man",
        period: "2015",
        date: "17. Juli 2015",
        slug: "ant-man",
        story: [
          "Hank Pym hütet seit Jahrzehnten seine Pym-Partikel, die Materie schrumpfen lassen. Sein Ex-Protegé Darren Cross steht kurz davor, die Technik als Waffe neu zu erfinden.",
          "Der frisch entlassene Einbrecher Scott Lang stiehlt bei einem vermeintlichen Routine-Job Pyms Ant-Man-Anzug. In Wahrheit hatte Pym den Einbruch als Test eingefädelt.",
          "Pym und seine Tochter Hope bilden Scott im Schrumpfen, im Kämpfen und im Kommandieren von Ameisen aus.",
          "Pyms Frau Janet ging einst als Wasp verloren, als sie subatomar schrumpfte und im Quantenraum verschwand.",
          "Bei einem Zwischenstopp im Avengers-Hauptquartier liefert sich Scott einen Kampf mit Falcon und gewinnt knapp.",
          "Cross will seinen Yellowjacket-Anzug an HYDRA verkaufen. Beim finalen Duell schrumpft Scott subatomar, zerstört den Anzug von innen und findet als Erster den Weg aus dem Quantenraum zurück.",
          "Hank zeigt Hope daraufhin einen neuen Wasp-Anzug. Falcon merkt sich derweil: „Ich kenne da einen Typen.“",
        ],
        characters: ["Scott Lang / Ant-Man", "Hank Pym", "Hope van Dyne", "Darren Cross / Yellowjacket"],
      },
    ],
  },
  {
    num: 3,
    id: "phase-3",
    title: "Phase Three",
    saga: "The Infinity Saga",
    years: "2016 – 2019",
    accent: "#ffd93c",
    nebula: [[255, 214, 66], [235, 160, 40], [70, 90, 210]],
    movies: [
      {
        title: "Captain America: Civil War",
        period: "2016",
        date: "6. Mai 2016",
        slug: "captain-america-civil-war",
        story: [
          "Eine Avengers-Mission in Lagos endet mit zivilen Opfern. Als Konsequenz sollen die Sokovia-Verträge das Team unter UN-Kontrolle stellen.",
          "Tony unterstützt die Verträge aus Schuldgefühlen, Steve lehnt sie ab, und die Avengers spalten sich in zwei Lager.",
          "Bei einem Anschlag in Wien stirbt König T'Chaka. Die Beweise deuten auf Bucky, und T'Challa schwört als Black Panther Rache.",
          "In Wahrheit zieht Helmut Zemo die Fäden. Er verlor seine Familie in Sokovia und will die Avengers von innen zerstören, indem er mit HYDRA-Codewörtern Buckys Programmierung aktiviert.",
          "Am Flughafen Leipzig eskaliert der Streit zur Schlacht Team Cap gegen Team Iron Man, mit den Debüts von Spider-Man und Giant-Man. Rhodey stürzt ab und bleibt gelähmt.",
          "In Sibirien spielt Zemo sein letztes Ass aus. Der Winter Soldier ermordete 1991 Tonys Eltern, und Steve wusste davon.",
          "Nach dem bitteren Zweikampf lässt Steve den Schild zurück. T'Challa fasst Zemo und gewährt Bucky Asyl im Kryoschlaf in Wakanda.",
          "Zum Schluss befreit Steve seine Mitstreiter aus dem Hochsicherheitsgefängnis Raft. Die Avengers sind zerbrochen.",
        ],
        characters: ["Captain America", "Iron Man", "Bucky Barnes", "Black Panther", "Spider-Man", "Helmut Zemo", "Black Widow", "Wanda Maximoff"],
      },
      {
        title: "Black Widow",
        period: "2016",
        date: "9. Juli 2021",
        slug: "black-widow",
        story: [
          "1995 flieht Natashas Scheinfamilie aus den USA: die „Eltern“ Alexei und Melina sowie die kleine „Schwester“ Yelena. Die Mädchen werden an den Red Room ausgeliefert.",
          "In der Gegenwart, auf der Flucht nach Civil War, erreicht Natasha ein Paket von Yelena mit einem Gegenmittel gegen die chemische Gehirnwäsche der Witwen.",
          "Die Schwestern decken auf, dass Dreykov noch lebt und der Red Room als fliegende Festung voller willenloser Agentinnen weiter existiert.",
          "Auf sie angesetzt ist Taskmaster, der jeden Kampfstil kopiert. Dahinter steckt Dreykovs eigene Tochter Antonia.",
          "Gemeinsam mit dem aus dem Gulag befreiten Alexei und Melina infiltriert Natasha den Red Room.",
          "Natasha stellt Dreykov und befreit die Witwen mit dem Gegenmittel. Yelena bringt die Festung zum Absturz, und Dreykov stirbt.",
          "Die Abspannszene spielt nach Endgame an Natashas Grab. Dort gibt Valentina Yelena ein neues Ziel: Clint Barton.",
        ],
        characters: ["Natasha Romanoff", "Yelena Belova", "Alexei / Red Guardian", "Melina Vostokoff", "Taskmaster", "General Dreykov"],
      },
      {
        title: "Black Panther",
        period: "2016",
        date: "16. Feb. 2018",
        slug: "black-panther",
        story: [
          "Nach T'Chakas Tod besteigt T'Challa den Thron des verborgenen Hightech-Königreichs Wakanda.",
          "Auf dem Land lastet eine alte Schuld. 1992 tötete T'Chaka in Oakland seinen eigenen Bruder N'Jobu, der Wakandas Waffen exportieren wollte, und ließ dessen kleinen Sohn Erik zurück.",
          "Der Waffenhändler Ulysses Klaue taucht mit gestohlenem Vibranium auf. Nach der Verfolgungsjagd in Busan tötet Killmonger ihn und verschafft sich damit seine Eintrittskarte nach Wakanda.",
          "Killmonger fordert den Ritualkampf, besiegt T'Challa und stürzt ihn den Wasserfall hinab. Als neuer König will er Wakandas Waffen an Unterdrückte in aller Welt verteilen.",
          "Von den Jabari um M'Baku gerettet, kehrt T'Challa zurück und stellt sich Killmonger ein zweites Mal.",
          "Tödlich verwundet lehnt Killmonger die Heilung ab: „Begrabt mich im Meer, bei meinen Vorfahren, die von den Schiffen sprangen.“",
          "T'Challa beendet Wakandas Isolation und öffnet Wissen und Hilfe des Landes erstmals der Welt.",
        ],
        characters: ["T'Challa / Black Panther", "Erik Killmonger", "Shuri", "Okoye", "Nakia", "M'Baku"],
      },
      {
        title: "Spider-Man: Homecoming",
        period: "2016",
        date: "7. Juli 2017",
        slug: "spider-man-homecoming",
        streaming: ["prime"],
        story: [
          "Nach dem Einsatz in Berlin will Peter unbedingt beweisen, dass er ein echter Avenger sein kann, doch Tony hält ihn bewusst auf Abstand.",
          "Adrian Toomes sammelt seit der Schlacht um New York heimlich Alien-Technologie und verkauft daraus gebaute Waffen als geflügelter Vulture.",
          "Peters Alleingang auf der Staten-Island-Fähre endet im Desaster. Tony nimmt ihm den Anzug ab, denn wenn er ohne den Anzug nichts sei, solle er ihn auch nicht haben.",
          "Der Schock-Twist am Homecoming-Abend zeigt, dass Toomes der Vater von Liz ist, Peters Date.",
          "Im selbstgenähten Anzug stoppt Peter Toomes' Überfall auf das Stark-Frachtflugzeug und rettet ihn anschließend sogar aus dem brennenden Wrack.",
          "Peter lehnt Tonys Angebot ab, offiziell Avenger zu werden. In der letzten Szene entdeckt Tante May sein Geheimnis.",
        ],
        characters: ["Peter Parker / Spider-Man", "Tony Stark", "Adrian Toomes / Vulture", "Ned Leeds", "May Parker"],
      },
      {
        title: "Doctor Strange",
        period: "2016 – 2017",
        date: "4. Nov. 2016",
        slug: "doctor-strange",
        story: [
          "Ein Autounfall zerstört die Hände des brillanten, arroganten Neurochirurgen Stephen Strange und damit seine Karriere.",
          "Die verzweifelte Suche nach Heilung führt ihn nach Kamar-Taj, wo die Ancient One ihm Astralebene, Multiversum und die Mystischen Künste offenbart.",
          "Der abtrünnige Zelot Kaecilius hat ein Ritual gestohlen, um Dormammu im Tausch gegen ewiges Leben aus der Dunklen Dimension zu rufen.",
          "Strange entdeckt im Auge von Agamotto den Zeitstein und wird vom eigenwilligen Cloak of Levitation erwählt.",
          "Die sterbende Ancient One gesteht ihm, dass auch sie ihre Langlebigkeit heimlich aus der Dunklen Dimension bezog.",
          "Strange fängt Dormammu in einer endlosen Zeitschleife mit den Worten „Dormammu, ich bin gekommen, um zu verhandeln“, bis der Dämon entnervt aufgibt und samt Zeloten abzieht.",
          "Mordo wendet sich enttäuscht von den Regelbrüchen der Zauberer ab. In der Abspannszene bietet Strange Thor seine Hilfe an.",
        ],
        characters: ["Stephen Strange", "The Ancient One", "Karl Mordo", "Wong", "Kaecilius"],
      },
      {
        title: "Thor: Ragnarok",
        period: "2017",
        date: "3. Nov. 2017",
        slug: "thor-ragnarok",
        story: [
          "Thor besiegt den Feuerdämon Surtur und verhindert damit scheinbar Ragnarök. Daheim entlarvt er dann Loki, der seit Jahren als falscher Odin regiert.",
          "Odin stirbt in Norwegen, und damit wird Hela frei, Odins verstoßene Erstgeborene und Göttin des Todes. Sie zerschmettert Mjölnir mit einer Hand.",
          "Thor und Loki stranden auf dem Müllplaneten Sakaar, wo der Grandmaster Gladiatorenkämpfe veranstalten lässt.",
          "In der Arena wartet der amtierende Champion, der seit Sokovia verschollene Hulk.",
          "Mit Valkyrie, der letzten Überlebenden von Odins Walküren, fliehen sie durch ein Wurmloch nach Asgard, das Hela längst erobert hat.",
          "Thor verliert im Kampf ein Auge und begreift, dass seine Macht nicht im Hammer steckt und Asgard kein Ort ist, sondern sein Volk.",
          "Um Hela zu vernichten, lässt Thor Ragnarök bewusst geschehen. Loki entfesselt Surtur, Asgard vergeht, und das Volk entkommt auf einem Raumschiff.",
          "Loki nimmt heimlich den Tesserakt mit. Nach dem Abspann fängt ein gewaltiges Schiff die Flüchtlinge ab, das Thanos gehört.",
        ],
        characters: ["Thor", "Hulk", "Loki", "Hela", "Valkyrie", "Grandmaster", "Heimdall"],
      },
      {
        title: "Ant-Man and the Wasp",
        period: "2018",
        date: "6. Juli 2018",
        slug: "ant-man-and-the-wasp",
        story: [
          "Nach Civil War steht Scott unter Hausarrest, bis ihn eine Traumbotschaft aus dem Quantenraum erreicht, die verrät, dass Janet noch lebt.",
          "Hank und Hope holen Scott kurzerhand aus dem Hausarrest und bauen einen Quantentunnel, um Janet nach 30 Jahren zu bergen.",
          "Ghost alias Ava Starr phast seit einem Quantenunfall unkontrolliert durch Materie und stiehlt das schrumpfbare Labor, weil sie Janets Quantenenergie zum Überleben braucht.",
          "Zwischen Waffenhändler Sonny Burch, dem FBI und Ghost jagen alle dem Koffer-Labor durch San Francisco hinterher.",
          "Janet wird tatsächlich aus dem Quantenraum gerettet und stabilisiert Ava mit einem Teil ihrer Energie.",
          "Die Mid-Credit-Szene ändert alles. Während Scott im Quantenraum Partikel sammelt, zerfallen Hank, Janet und Hope durch Thanos' Snap zu Staub, und Scott sitzt fest.",
        ],
        characters: ["Scott Lang", "Hope van Dyne / Wasp", "Hank Pym", "Janet van Dyne", "Ava Starr / Ghost"],
      },
      {
        title: "Avengers: Infinity War",
        period: "2018",
        date: "27. Apr. 2018",
        slug: "avengers-infinity-war",
        story: [
          "Thanos überfällt das Flüchtlingsschiff der Asgardier. Heimdall und Loki sterben, Thanos nimmt den Raumstein aus dem Tesserakt, und der Hulk wird im letzten Moment zur Erde gerettet.",
          "In New York verteidigen Strange, Tony und Peter den Zeitstein. Sie landen auf dem Schiff der Black Order und fliegen Thanos' Heimatwelt Titan entgegen.",
          "Thor schmiedet mit Rocket und Groot auf Nidavellir die Axt Stormbreaker samt Bifröst-Kraft.",
          "Auf Vormir opfert Thanos unter Tränen Gamora und erhält dafür den Seelenstein. Hüter des Steins ist ausgerechnet Red Skull.",
          "Auf Titan scheitert der fast geglückte Plan an Quills Wut über Gamoras Tod. Strange tauscht den Zeitstein gegen Tonys Leben, denn er sah 14.000.605 mögliche Zukünfte und nur einen einzigen Sieg.",
          "In Wakanda soll Shuri den Gedankenstein aus Vision entfernen. Als die Zeit abläuft, zerstört Wanda Stein und Vision selbst, doch Thanos dreht die Zeit zurück und reißt den Stein heraus.",
          "Thor rammt Stormbreaker in Thanos' Brust, aber nicht in den Kopf. Thanos schnippt, und die Hälfte allen Lebens im Universum zerfällt zu Staub.",
          "Nach dem Abspann funkt Fury im letzten Moment einen Pager an, auf dem das Logo von Captain Marvel erscheint.",
        ],
        characters: ["Thanos", "Iron Man", "Doctor Strange", "Spider-Man", "Thor", "Captain America", "Die Guardians", "Wanda & Vision"],
      },
      {
        title: "Avengers: Endgame",
        period: "2018 – 2023",
        date: "26. Apr. 2019",
        slug: "avengers-endgame",
        story: [
          "Carol rettet Tony und Nebula aus dem All. Die Avengers spüren Thanos auf, doch er hat die Steine längst zerstört, und Thor enthauptet ihn im Zorn.",
          "Fünf Jahre später entkommt Scott durch Zufall aus dem Quantenraum, wo für ihn nur fünf Stunden vergingen, und bringt die Idee eines „Zeit-Heists“ mit.",
          "Tony, inzwischen Vater der kleinen Morgan, knackt die Zeitreise-Formel. Banner ist jetzt Smart Hulk, und Thor vegetiert gebrochen in Neu-Asgard.",
          "Die Missionen führen nach New York 2012, Asgard 2013 sowie Morag und Vormir 2014 und ins Jahr 1970, wo Steve Peggy wiedersieht und Tony sich mit seinem Vater aussöhnt.",
          "Auf Vormir opfert sich Natasha im Ringen mit Clint für den Seelenstein.",
          "Hulks Schnippen holt als „Blip“ alle Ausgelöschten zurück. Doch die 2014er-Nebula hat den Plan verraten, und der damalige Thanos springt mit seiner Armee in die Gegenwart.",
          "In der finalen Schlacht führt Cap Mjölnir, und durch Stranges Portale kehren alle Verschwundenen zurück: „Avengers... assemble!“",
          "Tony reißt die Steine an sich mit den Worten „I am Iron Man“ und löscht Thanos samt Armee mit einem letzten Schnippen aus. Die Energie tötet ihn.",
          "Steve bringt die Steine in ihre Zeiten zurück und bleibt in der Vergangenheit bei Peggy. Als alter Mann übergibt er den Schild an Sam Wilson.",
        ],
        characters: ["Iron Man", "Captain America", "Thor", "Hulk", "Black Widow", "Hawkeye", "Thanos", "Captain Marvel"],
      },
    ],
  },
  {
    num: 4,
    id: "phase-4",
    title: "Phase Four",
    saga: "The Multiverse Saga",
    years: "2021 – 2022",
    accent: "#a855f7",
    nebula: [[170, 82, 255], [96, 56, 230], [52, 120, 220]],
    movies: [
      {
        title: "Loki – Staffel 1",
        period: "2012 · TVA",
        date: "9. Juni 2021",
        slug: "loki",
        series: true,
        story: [
          "Der Loki des Jahres 2012, während Endgames Zeit-Heist mit dem Tesserakt entkommen, wird von der Time Variance Authority verhaftet.",
          "Die TVA wacht im Auftrag der Zeit-Hüter über die eine „Heilige Zeitlinie“ und löscht jede Abweichung. Agent Mobius rekrutiert Loki als Berater.",
          "Das Ziel ist eine mordende Loki-Variante namens Sylvie, die TVA-Trupps auslöscht und einen Großangriff plant.",
          "Auf dem dem Untergang geweihten Mond Lamentis kommen Loki und Sylvie sich näher. Genau dieses Nexus-Ereignis verrät sie an die TVA.",
          "Über die Behörde kommt die Wahrheit ans Licht, dass alle Mitarbeiter selbst Varianten mit gelöschten Erinnerungen sind und die Zeit-Hüter nur leblose Puppen.",
          "Jenseits des Voids am Ende der Zeit wartet in einer Zitadelle „Der da bleibt“. Er beendete einst den Krieg seiner Varianten und hält seither das Multiversum auf eine einzige Zeitlinie beschnitten.",
          "Trotz aller Warnungen tötet Sylvie ihn. Die Zeitlinie verzweigt unkontrolliert, und das Multiversum ist entfesselt.",
          "Loki strandet in einer fremden TVA, in der Mobius ihn nicht kennt. Dort steht eine Statue des Mannes, der eben noch starb.",
        ],
        characters: ["Loki", "Sylvie", "Mobius", "Ravonna Renslayer", "Miss Minutes", "Der da bleibt"],
      },
      {
        title: "WandaVision",
        period: "2023",
        date: "15. Jan. 2021",
        slug: "wandavision",
        series: true,
        story: [
          "Wanda und Vision leben eine perfekte Sitcom-Ehe, die sich Jahrzehnt für Jahrzehnt weiterdreht. Dabei ist Vision eigentlich tot, und die Störungen im Bild häufen sich.",
          "Draußen belagern S.W.O.R.D., Monica Rambeau, Darcy und Jimmy Woo die Stadt. Ganz Westview ist in Wandas „Hex“ gefangen, und alle Bewohner sind Statisten wider Willen.",
          "Der Ursprung liegt in überwältigender Trauer, aus der Wanda unbewusst die gesamte Illusion erschuf, samt neuem Vision und den Zwillingen Billy und Tommy.",
          "Nachbarin „Agnes“ ist in Wahrheit die jahrhundertealte Hexe Agatha Harkness, die es auf Wandas Magie abgesehen hat: „Agatha All Along“.",
          "Agatha spricht aus, was Wanda ist, nämlich die Scarlet Witch, Trägerin von Chaosmagie und mächtiger als der Sorcerer Supreme.",
          "S.W.O.R.D.-Direktor Hayward reaktiviert derweil Visions Leiche als White Vision. Die beiden Visionen beenden ihren Kampf mit einem Gedankenexperiment statt mit Gewalt.",
          "Wanda sperrt Agatha in ihre Nachbarinnen-Rolle und löst den Hex auf. Damit verliert sie Vision und die Kinder ein zweites Mal.",
          "In der Abspannszene studiert Wanda in einer einsamen Berghütte den Darkhold und hört ihre Kinder um Hilfe rufen.",
        ],
        characters: ["Wanda Maximoff", "Vision", "Agatha Harkness", "Monica Rambeau", "Darcy Lewis", "Jimmy Woo"],
      },
      {
        title: "Shang-Chi and the Legend of the Ten Rings",
        period: "2024",
        date: "3. Sep. 2021",
        slug: "shang-chi",
        story: [
          "Seit tausend Jahren führt Wenwu mit der Macht der Zehn Ringe seine Schattenorganisation, bis er sich in Ying Li verliebt, die Wächterin des verborgenen Dorfes Ta Lo.",
          "Nach Lis Ermordung drillte Wenwu den gemeinsamen Sohn Shang-Chi zum Attentäter. Mit 14 floh der Junge und lebt seither als „Shaun“ in San Francisco.",
          "Wenwus Männer spüren ihn auf und rauben im Bus-Kampf Shang-Chis Amulett und in Macau das seiner Schwester Xialing. Zusammen weisen die Anhänger den Weg nach Ta Lo.",
          "Wenwu hört hinter einem versiegelten Tor in Ta Lo die Stimme seiner toten Frau. In Wahrheit lockt ihn der dort gefangene Seelenfresser.",
          "Shang-Chi, Katy und Xialing fliehen nach Ta Lo und bereiten sich mit Tante Ying Nan und dem Dorf auf die Schlacht vor.",
          "Wenwu sprengt das Tor auf. Im Sterben übergibt er Shang-Chi die Zehn Ringe, mit denen dieser an der Seite der Großen Beschützerin den Seelenfresser vernichtet.",
          "In der Abspannszene untersuchen Wong, Captain Marvel und Bruce Banner die Ringe, die ein Signal an ein unbekanntes Ziel senden. Xialing übernimmt derweil die Organisation ihres Vaters.",
        ],
        characters: ["Shang-Chi", "Katy", "Wenwu / Mandarin", "Xialing", "Trevor Slattery"],
      },
      {
        title: "The Falcon and the Winter Soldier",
        period: "2024",
        date: "19. März 2021",
        slug: "the-falcon-and-the-winter-soldier",
        series: true,
        story: [
          "Sam gibt Caps Schild ans Smithsonian, doch die Regierung ernennt kurzerhand einen eigenen neuen Captain America namens John Walker.",
          "Die Flag Smashers um Karli Morgenthau, verstärkt durch Supersoldaten-Serum, kämpfen für die Menschen, die nach der Rückkehr der Verschwundenen entwurzelt wurden.",
          "Sam und Bucky ermitteln widerwillig gemeinsam, holen Zemo aus dem Gefängnis und stoßen in Madripoor auf den „Power Broker“, hinter dem sich Sharon Carter verbirgt.",
          "Sie treffen Isaiah Bradley, einen schwarzen Supersoldaten aus den 50ern, den die eigene Regierung einsperrte und aus der Geschichte tilgte.",
          "Nach dem Tod seines Partners Lemar exekutiert Walker vor laufenden Kameras einen Flag Smasher mit dem Schild. Titel und Schild werden ihm daraufhin entzogen.",
          "Sam nimmt das Vermächtnis an und rettet im neuen Anzug aus Wakanda als Captain America den GRC-Gipfel. Karli stirbt durch Sharons Schuss.",
          "Isaiah erhält seinen Platz im Smithsonian. Walker wird von Valentina als „U.S. Agent“ rekrutiert.",
        ],
        characters: ["Sam Wilson / Falcon", "Bucky Barnes", "John Walker", "Karli Morgenthau", "Helmut Zemo", "Sharon Carter"],
      },
      {
        title: "Spider-Man: Far From Home",
        period: "2024",
        date: "2. Juli 2019",
        slug: "spider-man-far-from-home",
        streaming: ["prime"],
        story: [
          "Monate nach dem Blip trauert Peter um Tony und will auf der Europa-Klassenfahrt eigentlich nur MJ näherkommen. Furys Anrufe drückt er weg.",
          "In Venedig und Prag greifen die „Elementare“ an, bekämpft von Quentin Beck alias Mysterio, angeblich ein Held aus einem zerstörten Parallel-Universum.",
          "Tony hat Peter EDITH vermacht, eine Brille mit Zugriff auf das gesamte Stark-Arsenal. Der überforderte Peter übergibt sie ausgerechnet Beck.",
          "Der Twist offenbart, dass Beck ein gefeuerter Stark-Entwickler ist und die Elementare Illusionen aus Drohnen und Projektoren sind, alles inszeniert, um an EDITH zu kommen.",
          "Becks Illusions-Albtraum endet damit, dass Peter in Berlin von einem Zug erfasst wird. Mit Happys Hilfe und selbstgebautem Anzug fliegt er nach London.",
          "Im Finale durchschaut Peter die Illusionen mit seinem „Peter-Tingle“. Beck stirbt durch eine fehlgeleitete eigene Drohne.",
          "Die Mid-Credit-Szene schlägt ein wie eine Bombe. Ein manipuliertes Video macht Peter zum Mörder Mysterios und enthüllt der ganzen Welt seine Identität.",
        ],
        characters: ["Peter Parker / Spider-Man", "Quentin Beck / Mysterio", "MJ", "Nick Fury", "Happy Hogan"],
      },
      {
        title: "Eternals",
        period: "2024",
        date: "5. Nov. 2021",
        slug: "eternals",
        story: [
          "Vor 7000 Jahren schickte der Celestial Arishem zehn Eternals zur Erde, um die monströsen Deviants zu jagen. In die Konflikte der Menschen dürfen sie nicht eingreifen.",
          "In der Gegenwart tauchen die Deviants plötzlich wieder auf. Anführerin Ajak wird tot aufgefunden, und Sersi erbt die Verbindung zu Arishem.",
          "Die Wahrheit lautet, dass die Eternals synthetische Wesen sind und in der Erde der Celestial Tiamut heranreift, dessen Schlüpfen als „Emergence“ den Planeten zerstören würde.",
          "Ikaris wusste es die ganze Zeit und lieferte Ajak den Deviants aus, um Arishems Plan zu schützen.",
          "Im vereinten „Uni-Mind“ bündelt das Team seine Kräfte, und Sersi versteinert den erwachenden Tiamut mitten im Indischen Ozean.",
          "Der zerrissene Ikaris fliegt in die Sonne. Sprite gibt ihre Unsterblichkeit auf und wird ein normaler Mensch.",
          "Arishem entführt Sersi, Phastos und Kingo, um über die Erde zu richten. In den Abspannszenen treten Thanos' Bruder Eros und Dane Whitmans Ebony Blade auf.",
        ],
        characters: ["Sersi", "Ikaris", "Thena", "Kingo", "Sprite", "Druig", "Makkari", "Phastos", "Ajak"],
      },
      {
        title: "Spider-Man: No Way Home",
        period: "2024",
        date: "17. Dez. 2021",
        slug: "spider-man-no-way-home",
        streaming: ["prime"],
        story: [
          "Nach Mysterios Enthüllung wird Peters Leben zerlegt durch Anklage und Dauerbelagerung, und MJ, Ned und er werden vom MIT abgelehnt.",
          "Peter bittet Strange um einen Vergessenszauber. Weil er ständig Ausnahmen hineinredet, gerät der Zauber außer Kontrolle.",
          "Aus dem Multiversum fallen Besucher, die Peters Identität kennen, darunter Doc Ock, Green Goblin, Electro, Sandman und Lizard.",
          "Statt sie in ihren sicheren Tod zurückzuschicken, will Peter die Schurken auf Mays Drängen heilen. Der Goblin sabotiert den Versuch, und May stirbt mit den Worten: „Mit großer Macht kommt große Verantwortung.“",
          "Ned öffnet mit Stranges Sling-Ring versehentlich Portale, aus denen zwei weitere Peter Parker treten.",
          "An der Freiheitsstatue heilen die drei Spider-Men gemeinsam alle Schurken. Der eine Peter rettet MJ vor dem Sturz, der andere fällt Hollands Racheschlag gegen den Goblin in den Arm.",
          "Um das aufreißende Multiversum zu retten, lässt Peter die ganze Welt vergessen, dass Peter Parker existiert, auch MJ und Ned.",
          "Peter beginnt allein von vorn, in einer kleinen Wohnung und mit selbstgenähtem Anzug.",
        ],
        characters: ["Peter Parker (Holland, Maguire & Garfield)", "Doctor Strange", "Green Goblin", "Doc Ock", "Electro", "MJ", "Ned"],
      },
      {
        title: "Doctor Strange in the Multiverse of Madness",
        period: "2025",
        date: "6. Mai 2022",
        slug: "doctor-strange-in-the-multiverse-of-madness",
        story: [
          "America Chavez kann als einziges Wesen durchs Multiversum reisen, unkontrolliert und immer in Momenten der Todesangst. Dämonen jagen sie bis zu Strange nach New York.",
          "Die Auftraggeberin ist Wanda selbst. Vom Darkhold korrumpiert, will sie Americas Kraft, um für immer in einem Universum bei ihren Söhnen Billy und Tommy zu leben.",
          "Als Scarlet Witch massakriert sie Kamar-Taj. Strange und America stürzen quer durch die Realitäten bis zur Erde-838.",
          "Dort tagen die Illuminati mit Professor X, Captain Carter, Captain Marvel, Black Bolt, Mister Fantastic und Mordo. Wanda dreamwalkt in ihr 838-Ich und tötet sie fast alle.",
          "Strange greift selbst zum verbotenen Darkhold-Dreamwalking. Er fährt in seine eigene Leiche und stellt sich Wanda am Berg Wundagore.",
          "America bringt Wanda zu „ihren“ Kindern, die vor ihr zurückweichen. Wanda erkennt, was sie geworden ist, und begräbt den Darkhold in allen Universen unter dem einstürzenden Wundagore.",
          "Strange trägt als Rechnung für den Darkhold fortan ein drittes Auge. In der Abspannszene holt ihn die Zauberin Clea in die Dunkle Dimension.",
        ],
        characters: ["Doctor Strange", "Wanda Maximoff / Scarlet Witch", "America Chavez", "Wong", "Christine Palmer"],
      },
      {
        title: "Hawkeye",
        period: "Dez. 2024",
        date: "24. Nov. 2021",
        slug: "hawkeye",
        series: true,
        story: [
          "Weihnachten in New York: Die junge Kate Bishop, seit der Chitauri-Invasion ein Hawkeye-Fan, stolpert über den Ronin-Anzug und zieht damit Clints dunkle Vergangenheit ans Licht.",
          "Als Ronin richtete Clint während der Blip-Jahre Verbrecher hin, und die Tracksuit Mafia will Rache an dem Mann im Anzug.",
          "Deren Anführerin Maya Lopez alias Echo macht Ronin für den Tod ihres Vaters verantwortlich. Bestellt hatte den Mord in Wahrheit ihr Ziehvater Kingpin.",
          "Auch Yelena mischt mit, von Valentina beauftragt, denn sie hält Clint für den Schuldigen an Natashas Tod.",
          "Kates Mutter Eleanor arbeitet für Kingpin und ließ einen drohenden Mitwisser beseitigen.",
          "Im Finale nimmt Clint Yelena die Wut, indem er ihr von Natashas Opfer erzählt. Kate stellt sich Kingpin, auf den am Ende Maya schießt.",
          "Clint nimmt Kate mit zu seiner Familie aufs Land, ein Neuanfang für beide Hawkeyes.",
        ],
        characters: ["Clint Barton / Hawkeye", "Kate Bishop", "Yelena Belova", "Maya Lopez / Echo", "Wilson Fisk / Kingpin"],
      },
      {
        title: "Deadpool & Wolverine",
        period: "2024 (TVA)",
        date: "26. Juli 2024",
        slug: "deadpool-and-wolverine",
        story: [
          "Wade hat das Heldendasein aufgegeben und verkauft Gebrauchtwagen, bis die TVA ihn abholt.",
          "Seine Welt verliert ihr „Anchor Being“, denn Logan ist tot, und Mr. Paradox will die dadurch sterbende Zeitlinie mit einem Time Ripper vorzeitig einäschern.",
          "Wade sucht im Multiversum einen Ersatz-Wolverine und findet den schlimmsten von allen, eine Variante, die einst ihre X-Men im Stich ließ.",
          "Paradox entsorgt beide im Void, wo Cassandra Nova herrscht, Charles Xaviers Zwillingsschwester.",
          "Im Void warten Widerstandskämpfer aus alten Marvel-Filmen wie Blade, Elektra, Gambit und X-23.",
          "Zurück in Wades Welt stellen sich Deadpool und Wolverine gemeinsam in den Strahl des Time Rippers, überleben dank geteilter Last und retten die Zeitlinie, die die TVA fortan bestehen lässt.",
          "Logan bleibt in Wades Universum und findet dort eine neue Ersatzfamilie inklusive Dogpool.",
        ],
        characters: ["Wade Wilson / Deadpool", "Logan / Wolverine", "Cassandra Nova", "Mr. Paradox", "Dogpool"],
      },
      {
        title: "Moon Knight",
        period: "2025",
        date: "30. März 2022",
        slug: "moon-knight",
        series: true,
        story: [
          "Museums-Souvenirverkäufer Steven Grant erwacht immer wieder an fremden Orten, denn er teilt sich seinen Körper aufgrund einer dissoziativen Identitätsstörung mit dem Söldner Marc Spector.",
          "Marc dient als Avatar des Mondgottes Khonshu. Sektenführer Arthur Harrow, selbst ein früherer Avatar, will die Göttin Ammit befreien, die „künftige Sünder“ schon vor der Tat richtet.",
          "Die Jagd nach dem goldenen Skarabäus führt Marc, Steven und Marcs Frau Layla zu Ammits Grab nach Ägypten.",
          "Harrow erschießt Marc. In einer Psychiatrie-Zwischenwelt der Duat erleben Marc und Steven ihre Kindheit, in der Marc nach dem Ertrinken des Bruders und den Misshandlungen der Mutter die Persönlichkeit Steven erschuf.",
          "Steven stürzt in die Dünen und erstarrt. Marc verweigert das Paradies ohne ihn, und gemeinsam kehren sie durch Osiris' Tor ins Leben zurück.",
          "Im Finale von Kairo bannen sie Ammit mit Laylas Hilfe, die kurzzeitig Avatar der Göttin Taweret wird, in Harrows Körper. Khonshu entlässt die beiden scheinbar aus seinem Dienst.",
          "Die Abspannszene enthüllt eine dritte Persönlichkeit namens Jake Lockley, der Harrow in Khonshus Auftrag erschießt.",
        ],
        characters: ["Marc Spector / Steven Grant / Moon Knight", "Layla El-Faouly", "Arthur Harrow", "Khonshu", "Ammit"],
      },
      {
        title: "Ms. Marvel",
        period: "2025",
        date: "8. Juni 2022",
        slug: "ms-marvel",
        series: true,
        story: [
          "Die Teenagerin Kamala Khan aus Jersey City, größter Captain-Marvel-Fan überhaupt, schmuggelt sich zur AvengerCon. Dort erweckt der Armreif ihrer Urgroßmutter Kräfte aus „hartem Licht“.",
          "Die Kräfte stammen aus der Noor-Dimension. Kamalas Urgroßmutter Aisha gehörte zu den Clandestines, verbannten Dschinn, die mit dem Armreif nach Hause wollen, selbst wenn das die Erde zerreißen würde.",
          "Die Familiengeschichte reicht bis zur Teilung Indiens 1947. In einer Zeitreise wird Kamala selbst zur „Spur aus Sternen“, die ihrer Großmutter Sana als Kind das Leben rettete.",
          "In Karachi trainiert Kamala mit den Red Daggers, während die Behörde Damage Control sie zu Hause zur Gefahr erklärt.",
          "Im Finale in Jersey City beschützt Kamala den entkräfteten Kamran. Ihr Vater erklärt ihr, dass ihr Name „Wunder“ bedeutet und sie schon immer ihre „Ms. Marvel“ war.",
          "Bruno entdeckt in Kamalas Genen eine Besonderheit, und zum ersten Mal im MCU fällt das Wort „Mutation“. In der Abspannszene tauscht der Armreif Kamala gegen Carol Danvers aus.",
        ],
        characters: ["Kamala Khan / Ms. Marvel", "Bruno Carrelli", "Nakia Bahadir", "Kamran", "Muneeba Khan"],
      },
      {
        title: "Thor: Love and Thunder",
        period: "2025",
        date: "8. Juli 2022",
        slug: "thor-love-and-thunder",
        story: [
          "Gorr verliert sein Kind in der Wüste und wird von seinem eigenen Gott verhöhnt. Das Necroschwert erwählt ihn, und fortan zieht er als Gorr der Götterschlächter los, um alle Götter zu töten.",
          "Thor hat sich bei den Guardians wieder in Form gebracht. In Neu-Asgard führt derweil Jane Foster Mjölnir, denn der zersplitterte Hammer hat sich für die krebskranke Jane als Mighty Thor neu zusammengesetzt.",
          "Gorr entführt die Kinder von Neu-Asgard ins Schattenreich, weil er sie als Köder für Stormbreaker braucht, seinen Schlüssel zum Bifröst.",
          "In Omnipotence City verweigert Zeus jede Hilfe. Im Handgemenge stiehlt Thor ihm kurzerhand den Blitz.",
          "Gorrs wahres Ziel ist Eternity, ein Wesen, das dem Ersten, der es erreicht, einen einzigen Wunsch erfüllt.",
          "Jede Verwandlung in Mighty Thor zehrt Janes letzte Kraft auf. Im entscheidenden Kampf opfert sie sich trotzdem.",
          "Vor Eternity wünscht sich der sterbende Gorr nicht die Vernichtung der Götter, sondern seine Tochter zurück. Thor nimmt das Mädchen an, „Love and Thunder“.",
          "Jane stirbt in Thors Armen und erreicht Walhalla. In der Abspannszene schickt der gedemütigte Zeus seinen Sohn Hercules los.",
        ],
        characters: ["Thor", "Jane Foster / Mighty Thor", "Gorr", "Valkyrie", "Korg", "Zeus"],
      },
      {
        title: "She-Hulk: Attorney at Law",
        period: "2025",
        date: "18. Aug. 2022",
        slug: "she-hulk",
        series: true,
        story: [
          "Nach einem Autounfall gerät Bruce' Blut in die Wunden seiner Cousine Jennifer Walters. Fortan ist die Anwältin die She-Hulk, behält aber anders als Bruce jederzeit die Kontrolle.",
          "Unfreiwillig geoutet, wird Jen Leiterin der neuen Kanzlei-Abteilung für Superhelden-Recht. Ihr erster Mandant ist Emil Blonsky, die geläuterte Abomination.",
          "Die Serie lebt von ihren Gästen wie Wong samt Partybekanntschaft Madisynn, einem Markenstreit gegen Titania um den Namen „She-Hulk“ und Matt Murdock, mit dem Jen mehr als nur einen Fall teilt.",
          "Die Hass-Website „Intelligencia“ um den anonymen HulkKing stiehlt Jens Blut und stellt sie auf einer Gala bloß. Ihr Wutausbruch bringt sie in Gewahrsam.",
          "Das Finale sprengt die vierte Wand komplett. Jen klettert aus dem Disney+-Menü ins Marvel-Studio und verhandelt mit der Drehbuch-KI K.E.V.I.N. ihr eigenes Serienende neu.",
          "Im neuen Ausgang wird Drahtzieher Todd verhaftet, Bruce präsentiert seinen Sohn Skaar, und Matt kommt zum Familienessen.",
        ],
        characters: ["Jennifer Walters / She-Hulk", "Bruce Banner", "Nikki Ramos", "Titania", "Matt Murdock / Daredevil"],
      },
      {
        title: "Black Panther: Wakanda Forever",
        period: "2025",
        date: "11. Nov. 2022",
        slug: "black-panther-wakanda-forever",
        story: [
          "T'Challa stirbt an einer Krankheit, weil das herzförmige Kraut vernichtet ist und Shuri es nicht rechtzeitig nachzüchten kann. Wakanda trauert, und Königin Ramonda regiert.",
          "Die Weltmächte jagen Vibranium. Ein CIA-Detektor spürt ein Vorkommen im Atlantik auf und weckt Talokan, das verborgene Unterwasserreich des Maya-Volks um Namor.",
          "Namor stellt Wakanda ein Ultimatum. Ausgeliefert werden soll die Erfinderin des Detektors, die 19-jährige MIT-Studentin Riri Williams, sonst droht Krieg.",
          "Talokan flutet Wakandas Hauptstadt. Königin Ramonda ertrinkt, als sie Riri rettet.",
          "Shuri synthetisiert das herzförmige Kraut aus Namors Pflanze neu und wird zum neuen Black Panther. Auf der Ahnenebene empfängt sie ausgerechnet Killmonger.",
          "Im finalen Duell ringt Shuri Namor nieder, verschont ihn aber, und aus dem Krieg wird ein stilles Bündnis.",
          "In Haiti verbrennt Shuri ihre Trauerkleidung. Nakia stellt ihr den kleinen Toussaint vor, T'Challas geheimen Sohn.",
        ],
        characters: ["Shuri", "Namor", "Okoye", "Königin Ramonda", "Riri Williams", "M'Baku"],
      },
    ],
  },
  {
    num: 5,
    id: "phase-5",
    title: "Phase Five",
    saga: "The Multiverse Saga",
    years: "2023 – 2025",
    accent: "#34d6a0",
    nebula: [[52, 214, 160], [32, 165, 125], [45, 110, 220]],
    movies: [
      {
        title: "Loki – Staffel 2",
        period: "TVA · zeitlos",
        date: "5. Okt. 2023",
        slug: "loki",
        series: true,
        story: [
          "Nach dem Tod von „Der da bleibt“ verzweigt die Zeit unaufhaltsam, und Loki „time-slippt“ unkontrolliert zwischen Vergangenheit und Gegenwart der TVA.",
          "Der Temporal Loom, der Zeit-Webstuhl der TVA, war nie für unendlich viele Zweige ausgelegt und droht zu kollabieren.",
          "Die Kang-Variante Victor Timely aus dem Jahr 1893 soll den Webstuhl retten, doch er zerfällt zu Fäden, als er ihn erreichen will.",
          "Loki durchschaut die Falle, denn der Loom kann gar nicht alle Zeitlinien fassen. Er ist ein Notschalter von „Der da bleibt“, der im Zweifel alles außer der Heiligen Zeitlinie kappt.",
          "Über gefühlte Jahrhunderte lernt Loki, sein Time-Slipping durch reinen Willen zu steuern, bis er jeden Moment gezielt ansteuern kann.",
          "Am Ende bleiben nur zwei Auswege, nämlich Sylvie töten oder alles verlieren. Loki wählt den dritten, indem er den Webstuhl zerstört und selbst an dessen Stelle tritt.",
          "Als Gott der Geschichten hält Loki fortan alle Zeitlinien wie einen lebenden Baum zusammen, allein auf dem Thron am Ende der Zeit.",
        ],
        characters: ["Loki", "Mobius", "Sylvie", "Ouroboros (O.B.)", "Victor Timely", "Miss Minutes"],
      },
      {
        title: "Ant-Man and the Wasp: Quantumania",
        period: "2025",
        date: "17. Feb. 2023",
        slug: "ant-man-and-the-wasp-quantumania",
        story: [
          "Cassie hat heimlich einen Sender in den Quantenraum gebaut, der prompt die ganze Familie hineinzieht: Scott, Hope, Cassie, Hank und Janet.",
          "Janet verschwieg 30 Jahre lang, was dort unten lauert. Sie traf einst den gestrandeten Kang und half ihm, bis sie in seinem Geist die Zerstörung ganzer Zeitlinien sah und seinen Antriebskern sabotierte.",
          "Der Quantenraum entpuppt sich als bewohnte Welt voller Städte und Freiheitskämpfer unter Kangs Schreckensherrschaft.",
          "Kangs Vollstrecker MODOK ist ein alter Bekannter, nämlich Darren Cross, der einstige Yellowjacket.",
          "Kang erpresst Scott mit Cassies Leben, den geschrumpften Antriebskern aus dem Herzen eines Wahrscheinlichkeits-Sturms zu bergen.",
          "Im großen Aufstand besiegen die Langs und das Volk des Quantenraums den Eroberer, der in seinen eigenen Kern gerissen wird, und die Familie kehrt heim.",
          "Die Mid-Credit-Szene zeigt das wahre Ausmaß, denn unzählige Kang-Varianten versammeln sich zum Rat, und der Eroberer war nur einer von vielen.",
        ],
        characters: ["Scott Lang", "Hope van Dyne", "Cassie Lang", "Janet van Dyne", "Hank Pym", "Kang der Eroberer", "MODOK"],
      },
      {
        title: "Guardians of the Galaxy Vol. 3",
        period: "2025",
        date: "5. Mai 2023",
        slug: "guardians-of-the-galaxy-vol-3",
        story: [
          "Adam Warlock schlägt auf Knowhere ein und verletzt Rocket schwer, doch die Not-OP blockiert ein Kill-Switch, den sein Schöpfer in ihn einbaute.",
          "Rückblenden zeigen Rockets Herkunft. Der High Evolutionary erschuf ihn in grausamen Tierversuchen, und seine einzigen Freunde waren Lylla, Teefs und Floor.",
          "Rocket war das einzige Versuchswesen mit echtem Genie, und genau dieses Gehirn will der High Evolutionary jetzt zurück.",
          "Für den Freischalt-Code bricht das Team in die Orgocorp-Zentrale ein, an ihrer Seite die 2014er-Gamora, die ihre alte Familie nicht mehr kennt.",
          "Auf Counter-Earth offenbart sich der Perfektionswahn des Schöpfers, denn jede Schöpfung, die ihm nicht genügt, wird vernichtet, ganze Welten inklusive.",
          "Rocket steht klinisch tot vor Lylla, doch der Code wird rechtzeitig geknackt: „Der Himmel ist noch nicht fertig mit dir.“",
          "Beim Sturm auf die Arête retten die Guardians sämtliche Kinder und Tiere an Bord. Rocket lässt seinen geschlagenen Schöpfer zurück.",
          "Beim Abschied kehrt Gamora zu den Ravagers zurück, Mantis geht ihren eigenen Weg, Nebula und Drax ziehen die geretteten Kinder groß, Quill besucht seinen Großvater auf der Erde, und Rocket führt die neuen Guardians an.",
        ],
        characters: ["Rocket", "Star-Lord", "Gamora (2014)", "Nebula", "Drax", "Mantis", "Groot", "High Evolutionary", "Adam Warlock"],
      },
      {
        title: "Secret Invasion",
        period: "2025",
        date: "21. Juni 2023",
        slug: "secret-invasion",
        series: true,
        story: [
          "Skrull-Rebellen um Gravik haben die Erde längst unterwandert, aus Zorn darüber, dass Fury sein altes Versprechen einer neuen Heimat nie einlöste.",
          "Graviks Plan ist es, einen Krieg zwischen den USA und Russland zu provozieren, damit die Menschheit sich selbst vernichtet und die Erde den Skrulls zufällt.",
          "Fury, vom Blip gezeichnet und ohne Avengers im Rücken, kämpft einen Schattenkrieg. Maria Hill stirbt gleich zu Beginn, erschossen von Gravik in Furys Gestalt.",
          "Die Enthüllungen sitzen tief, denn Rhodey ist seit langem ein Skrull-Doppelgänger, und Furys Ehefrau Priscilla ist die Skrull Varra.",
          "Talos stirbt bei einer Rettungsaktion. Seine Tochter G'iah wird zur Doppelagentin gegen Gravik.",
          "Im Finale um die „Harvest“, die gesammelte DNA der Avengers, werden Gravik und G'iah zu Super-Skrulls mit den Kräften aller Helden, und G'iah tötet ihn.",
          "Präsident Ritson erklärt alle Aliens zu Feinden. Zurück bleibt ein Klima totalen Misstrauens, während Fury zur Raumstation S.A.B.E.R. aufbricht.",
        ],
        characters: ["Nick Fury", "Talos", "Gravik", "G'iah", "Sonya Falsworth", "Präsident Ritson"],
      },
      {
        title: "Echo",
        period: "2025",
        date: "9. Jan. 2024",
        slug: "echo",
        series: true,
        story: [
          "Nach ihrem Schuss auf Kingpin flieht Maya Lopez aus New York in ihre Heimat Tamaha in Oklahoma, zu Großmutter Chula, Cousine Bonnie und Onkel Henry.",
          "Rückblenden erzählen ihre Choctaw-Ahnenreihe von der ersten Choctaw bis zu Mayas Mutter, deren Gaben in Maya weiterleben.",
          "Fisk hat den Schuss überlebt. Einst ließ er Mayas Vater töten, um sie als Ziehtochter an sich zu binden, und jetzt will er sie in sein Imperium zurückholen.",
          "Maya plant zunächst, Fisks Waffengeschäft selbst zu übernehmen, doch Familie und Ahnenerbe ziehen sie auf einen anderen Weg.",
          "Beim Pow-Wow-Finale nutzt Maya ihre neue Gabe nicht zum Töten, sondern berührt Fisks Kindheitstrauma und schickt ihn gebrochen fort.",
          "In der Abspannszene fasst Fisk einen neuen Plan, nämlich die Bürgermeisterwahl von New York.",
        ],
        characters: ["Maya Lopez / Echo", "Wilson Fisk / Kingpin", "Chula", "Bonnie", "Henry Lopez"],
      },
      {
        title: "The Marvels",
        period: "2026",
        date: "10. Nov. 2023",
        slug: "the-marvels",
        story: [
          "Die Kree-Anführerin Dar-Benn findet den Zwilling von Kamalas Armreif und reißt damit instabile Sprungpunkte in den Raum.",
          "Ihr Motiv ist der Tod ihres Planeten Hala, eine Spätfolge von Carols Zerstörung der Supreme Intelligence, die ihr bei den Kree den Hassnamen „Annihilator“ einbrachte.",
          "Dar-Benn stiehlt gezielt Lebensgrundlagen anderer Welten, etwa die Atmosphäre der Skrull-Zuflucht Tarnax und das Wasser von Aladna, und zuletzt will sie Carols Sonne.",
          "Der Haken ist, dass sich die Lichtkräfte von Carol, Monica und Kamala verschränkt haben, sodass die drei bei jeder Nutzung quer durchs All die Plätze tauschen.",
          "Aus der Zwangsgemeinschaft wird ein Team. Die drei trainieren ihre Wechsel und evakuieren nebenbei eine Raumstation mit Hilfe eines Schwarms Flerken-Katzen.",
          "Im Showdown stirbt Dar-Benn, reißt aber ein Loch in die Realität. Monica schließt es von der anderen Seite und bleibt in einem fremden Universum zurück.",
          "Kamala rekrutiert daheim in bester Fury-Manier Kate Bishop. In der Abspannszene erwacht Monica in einer Welt mit Binary und dem Beast der X-Men.",
        ],
        characters: ["Carol Danvers", "Monica Rambeau", "Kamala Khan / Ms. Marvel", "Dar-Benn", "Nick Fury"],
      },
      {
        title: "Agatha All Along",
        period: "2026",
        date: "18. Sep. 2024",
        slug: "agatha-all-along",
        series: true,
        story: [
          "Agatha erwacht machtlos aus Wandas Bann, gefangen in einer Krimi-Parodie ihres eigenen Lebens. Ein mysteriöser Teenager, dessen Name mit einem Siegel belegt ist, reißt sie heraus.",
          "„Teen“ will die legendäre Witches' Road gehen, an deren Ende jede Hexe erhält, was ihr fehlt. Agatha trommelt dafür einen Notbehelfs-Zirkel zusammen aus Lilia, Jennifer, Alice und Nachbarin Mrs. Hart.",
          "Mit ihnen wandert Rio Vidal, Agathas gefährliche alte Flamme, die in Wahrheit der Tod höchstpersönlich ist.",
          "Die Prüfungen der Road fordern ihre Opfer, denn Mrs. Hart und Alice sterben, und Lilia opfert sich in der Tarot-Prüfung.",
          "Teen ist Billy Maximoff, Wandas Sohn, dessen Seele beim Fall von Westview in den sterbenden William Kaplan fuhr.",
          "Der große Twist offenbart, dass die Witches' Road nie existierte. Sie war Agathas Lockmittel, um Hexen auszurauben, und wurde erst durch Billys Realitätskräfte wahr.",
          "Agatha opfert sich und nimmt mit einem Kuss den Tod auf sich, der Billy galt. Als Geist an seiner Seite sucht sie mit ihm nach Tommy, dem zweiten Zwilling.",
        ],
        characters: ["Agatha Harkness", "Billy Maximoff / Wiccan", "Rio Vidal", "Lilia Calderu", "Jennifer Kale", "Alice Wu-Gulliver"],
      },
      {
        title: "Captain America: Brave New World",
        period: "2026",
        date: "14. Feb. 2025",
        slug: "captain-america-brave-new-world",
        story: [
          "Sam ist als Captain America im Einsatz, als Präsident Thaddeus Ross ihm ein überraschendes Angebot macht, die Avengers unter der Regierung neu aufzubauen.",
          "Im Indischen Ozean ragt die versteinerte Celestial-Insel aus Eternals auf, der Fundort des neuen Wundermetalls Adamantium, um das die Weltmächte ringen.",
          "Beim Staatsempfang schießt ausgerechnet Isaiah Bradley auf den Präsidenten, ferngesteuert über Gedankenkontroll-Trigger.",
          "Der Drahtzieher ist Samuel Sterns, der seit seinem Gamma-Unfall in „The Incredible Hulk“ zum hyperintelligenten „Leader“ mutiert und von Ross jahrelang geheim gefangen gehalten wurde.",
          "Sterns' Manipulationen treiben die USA und Japan an den Rand eines Kriegs, den Sam und der neue Falcon Joaquin Torres in letzter Sekunde abwenden.",
          "Dann zündet Sterns' letzter Trumpf, das Gamma in Ross' Herztabletten. Der Präsident wird zum Red Hulk und verwüstet Washington, bis Sam ihn ohne Gewalt zur Aufgabe bewegt.",
          "Ross tritt zurück und geht in den Raft, und Isaiah wird rehabilitiert. Aus seiner Zelle warnt Sterns vor dem, was noch kommt.",
        ],
        characters: ["Sam Wilson / Captain America", "Thaddeus Ross / Red Hulk", "Joaquin Torres / Falcon", "Isaiah Bradley", "Samuel Sterns / The Leader"],
      },
      {
        title: "Daredevil: Born Again – Staffel 1",
        period: "2026",
        date: "4. März 2025",
        slug: "daredevil-born-again",
        series: true,
        story: [
          "Bullseye erschießt Foggy vor der Bar. Nach der Jagd über die Dächer lässt Matt ihn in die Tiefe stürzen und hängt das Daredevil-Kostüm entsetzt über sich selbst an den Nagel.",
          "Ein Jahr später führt Matt eine neue Kanzlei mit Kirsten McDuffie, und Wilson Fisk wird zum Bürgermeister von New York gewählt.",
          "Matt erstreitet den Freispruch für Hector Ayala alias White Tiger. Kurz darauf wird Ayala von einem korrupten Polizisten-Kult ermordet, der das Punisher-Totenkopfsymbol trägt.",
          "Der Serienmörder Muse, der mit dem Blut seiner Opfer malt, zwingt Matt endgültig zurück in die Maske.",
          "Fisk baut derweil seine Macht mit einer Anti-Vigilanten-Task-Force aus willfährigen Cops aus, während seine Ehe mit Vanessa in Machtspielen erstickt.",
          "Im Finale putscht sich Fisk faktisch zur Alleinherrschaft mit Ausnahmezustand und Jagd auf alle Maskierten. Matt, Karen und Frank Castle formieren den Widerstand aus dem Untergrund.",
        ],
        characters: ["Matt Murdock / Daredevil", "Wilson Fisk / Kingpin", "Frank Castle / Punisher", "Vanessa Fisk", "Muse", "Karen Page"],
      },
      {
        title: "Ironheart",
        period: "2026",
        date: "24. Juni 2025",
        slug: "ironheart",
        series: true,
        story: [
          "Riri Williams fliegt vom MIT, weil sie Kommilitonen gegen Geld die Arbeiten schreibt, und kehrt pleite nach Chicago zurück, wo sie ihren Anzug weiterbaut.",
          "Aus ihren Erinnerungen entsteht versehentlich die KI N.A.T.A.L.I.E., ein Abbild ihrer ermordeten besten Freundin Natalie.",
          "Für Geld schließt Riri sich der Crew von Parker Robbins an, dessen Kapuze ihm als The Hood dunkle magische Kräfte verleiht.",
          "Als Riri aussteigen will, macht der zunehmend von der Kapuze zerfressene Parker Jagd auf sie und ihre Familie.",
          "Mit Unterstützung von Natalies Familie und einem neuen Anzug besiegt Riri Parker und trennt ihn von der Kapuze.",
          "Dann folgt der folgenschwere Pakt, denn Mephisto, die Quelle der Kapuze, bietet Riri an, die echte Natalie zurückzubringen. Sie schlägt ein, und dunkle Adern zeichnen ihren Arm.",
        ],
        characters: ["Riri Williams / Ironheart", "Parker Robbins / The Hood", "N.A.T.A.L.I.E.", "Joe McGillicuddy", "Mephisto"],
      },
      {
        title: "Thunderbolts*",
        period: "2027",
        date: "2. Mai 2025",
        slug: "thunderbolts",
        story: [
          "CIA-Direktorin Valentina steht vor einem Untersuchungsausschuss und lässt ihre Söldner die Beweise vernichten, einschließlich der Söldner selbst. Yelena, John Walker, Ghost und Taskmaster sollen sich in einem Tresorlabor gegenseitig ausschalten.",
          "Im Labor wartet außerdem ein verwirrter Zivilist namens Bob, die einzige überlebende Testperson von Valentinas Supersoldaten-Projekt „Sentry“.",
          "Die Antihelden schlagen sich gemeinsam frei. Yelenas Ziehvater Alexei stößt als Red Guardian dazu, während Bucky Valentina als Kongressabgeordneter verfolgt.",
          "Valentina präsentiert Sentry als ihren goldenen Über-Avenger und verliert sofort die Kontrolle, als Bobs dunkle Seite erwacht, der Void.",
          "Der Void hüllt New York in Schwärze und löscht Menschen zu Schatten aus, und mit Superkräften ist ihm nicht beizukommen.",
          "Yelena geht freiwillig in die Dunkelheit und findet Bob in den Räumen seiner Traumata, und das Team folgt ihr. Geholt wird er nicht mit Gewalt, sondern mit Beistand.",
          "Valentina dreht den PR-Spieß um und präsentiert die Truppe der Welt als „New Avengers“. In der Abspannszene, 14 Monate später, erscheint am Himmel ein Schiff mit dem Logo der Fantastic Four.",
        ],
        characters: ["Yelena Belova", "Bucky Barnes", "Red Guardian", "Ghost", "John Walker / U.S. Agent", "Bob / Sentry", "Valentina Allegra de Fontaine"],
      },
    ],
  },
  {
    num: 6,
    id: "phase-6",
    title: "Phase Six",
    saga: "The Multiverse Saga",
    years: "2025 – 2027",
    accent: "#ffa63c",
    nebula: [[255, 160, 60], [255, 96, 48], [70, 84, 205]],
    movies: [
      {
        title: "The Fantastic Four: First Steps",
        period: "1960er · Erde-828",
        date: "25. Juli 2025",
        slug: "the-fantastic-four-first-steps",
        story: [
          "Auf der retro-futuristischen Erde-828 sind Reed, Sue, Johnny und Ben seit ihrem Weltraumflug durch kosmische Strahlung Superhelden und die gefeierte erste Familie ihrer Welt. Sue erwartet ein Kind.",
          "Die Silver Surferin Shalla-Bal erscheint am Himmel und verkündet, dass diese Welt auf dem Speiseplan von Galactus steht, dem Weltenverschlinger.",
          "Bei der Verhandlung im All macht Galactus ein Angebot. Er verschont die Erde im Tausch gegen das ungeborene Kind, in dem er die Power Cosmic spürt.",
          "Die Familie lehnt ab, und Franklin kommt auf der Flucht mitten im All zur Welt.",
          "Johnny entschlüsselt die Sprache der Surferin und erreicht sie damit, denn auch sie hat einst ihre eigene Welt geopfert, um ihre Heimat zu retten.",
          "Im Finale lockt die Familie Galactus mitten in New York vor ein Teleport-Portal. Sue stößt ihn mit letzter Kraft hindurch und stirbt dabei, doch der kleine Franklin erweckt sie wieder zum Leben.",
          "In der Abspannszene, Jahre später, steht ein Fremder mit grüner Kapuze und Maske bei Franklin, nämlich Doom.",
        ],
        characters: ["Reed Richards / Mister Fantastic", "Sue Storm / Invisible Woman", "Johnny Storm / Human Torch", "Ben Grimm / The Thing", "Galactus", "Silver Surfer"],
      },
      {
        title: "Wonder Man",
        period: "2026",
        date: "27. Jan. 2026",
        slug: "wonder-man",
        series: true,
        story: [
          "In dieser Hollywood-Satire unter dem Marvel-Spotlight-Banner bekommt der Superheldenklassiker „Wonder Man“ ein Reboot, und ganz Los Angeles will die Rolle.",
          "Mittendrin kämpft Schauspieler und Stuntman Simon Williams darum, endlich seinen Traumpart zu bekommen.",
          "An seiner Seite wittert Trevor Slattery, der einstige Fake-Mandarin, sein ganz großes Comeback.",
        ],
        characters: ["Simon Williams", "Trevor Slattery", "Regisseur Von Kovak"],
      },
      {
        title: "Daredevil: Born Again – Staffel 2",
        period: "2027",
        date: "24. März 2026",
        slug: "daredevil-born-again",
        series: true,
        story: [
          "Unter Fisks Ausnahmezustand werden in New York Vigilanten gejagt, und Daredevil kämpft aus dem Untergrund gegen das Regime des Bürgermeisters.",
          "An Matts Seite stehen Karen, Frank Castle und der wachsende Widerstand.",
          "Ihr MCU-Debüt gibt Jessica Jones, die superstarke Privatdetektivin aus den alten Netflix-Serien.",
        ],
        characters: ["Matt Murdock / Daredevil", "Wilson Fisk / Kingpin", "Jessica Jones", "Frank Castle / Punisher"],
      },
      {
        title: "Spider-Man: Brand New Day",
        period: "20??",
        date: "31. Juli 2026",
        slug: "spider-man-brand-new-day",
        streaming: ["cinema"],
        upcoming: true,
        story: [
          "Nach dem großen Vergessen ist Peter ganz auf sich allein gestellt und beginnt ein neues Kapitel als freundliche Spinne aus der Nachbarschaft.",
          "Angekündigt sind Auftritte von Punisher und Hulk. Die Handlung selbst hält Marvel noch unter Verschluss.",
        ],
        characters: ["Peter Parker / Spider-Man", "MJ", "Punisher (angekündigt)", "Hulk (angekündigt)"],
      },
      {
        title: "VisionQuest",
        period: "20??",
        date: "14. Okt. 2026",
        slug: "visionquest",
        series: true,
        upcoming: true,
        story: [
          "Im Finale der WandaVision-Trilogie sucht White Vision nach Erinnerung, Identität und dem, was von Vision in ihm übrig ist.",
          "Auf seinem Weg trifft er auf Ultron, erneut gesprochen von James Spader.",
        ],
        characters: ["Vision", "Ultron", "Jocasta (angekündigt)", "E.D.I.T.H. (angekündigt)"],
      },
      {
        title: "Avengers: Doomsday",
        period: "20??",
        date: "18. Dez. 2026",
        slug: "avengers-doomsday",
        streaming: ["cinema"],
        upcoming: true,
        story: [
          "Die Avengers treffen auf die Fantastic Four, die New Avengers, Veteranen der X-Men und auf Doctor Doom, gespielt von Robert Downey Jr.",
          "Details zur Handlung sind noch streng geheim.",
        ],
        characters: ["Doctor Doom", "Die Avengers", "Die Fantastic Four", "X-Men-Veteranen"],
      },
      {
        title: "Avengers: Secret Wars",
        period: "20??",
        date: "17. Dez. 2027",
        slug: "avengers-secret-wars",
        streaming: ["cinema"],
        upcoming: true,
        story: [
          "Das große Finale der Multiverse Saga, in dem die Schicksale aller Realitäten zusammenlaufen.",
          "Mehr ist noch nicht bekannt.",
        ],
        characters: ["Noch unbekannt"],
      },
    ],
  },
];

/* Nebelfarben, solange keine Phase aktiv ist (Hero/Seitenanfang):
   die Akzentfarben aller sechs Phasen – die Galaxie zeigt dort also das
   komplette Spektrum der Timeline. */
const DEFAULT_NEBULA = PHASES.map(p => {
  const n = parseInt(p.accent.slice(1), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
});
const DEFAULT_ACCENT = "#4d8cff";
